<?php


namespace amenities;


use App\Models\Admin;
use App\Models\Client;
use App\Models\Amenity;
use App\Models\Renter;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Tests\TestCase;

class AmenitiesTest extends TestCase
{
    use RefreshDatabase;

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
    }

    /** @test */
    public function getting_all_amenities()
    {
        Amenity::factory(2)->create();
        $response = $this->json('get','/amenities')
            ->assertStatus(200)
            ->assertSee(['success' => true])
            ->assertSee('data')
            ->assertJsonCount(2);

        $this->assertEquals(count($response->json(['data'])),2);
    }
    /** @test */
    public function an_admin_can_add_a_amenity()
    {
        $admin = Admin::factory()->create();
        $data = [
            'name' => 'NO KIDS'
        ];
        $this->actingAs($admin)->json('post','/amenities', $data)
            ->assertStatus(201);
        $this->assertDatabaseCount('amenities',1);
    }
    /** @test */
    public function a_renter_cannot_add_a_amenity()
    {
        $renter = Renter::factory()->create();
        $data = [
            'name' => 'NO KIDS'
        ];
        $this->actingAs($renter)->json('post','/amenities', $data)
            ->assertStatus(401);
        $this->assertDatabaseCount('amenities',0);
    }
    /** @test */
    public function a_client_cannot_add_an_amenity()
    {
        $client = Client::factory()->create();
        $data = [
            'name' => 'NO KIDS'
        ];
        $this->actingAs($client)->json('post','/amenities', $data)
            ->assertStatus(401);
        $this->assertDatabaseCount('amenities',0);
    }
    /** @test */
    public function an_amenity_name_is_required()
    {
        $admin = Admin::factory()->create();
        $data = [
            'name' => ''
        ];
        $this->actingAs($admin)->json('post','/amenities', $data)
            ->assertStatus(403);
        $this->assertDatabaseCount('amenities',0);
    }
    /** @test */
    public function an_admin_can_update_an_amenity()
    {
        $admin = Admin::factory()->create();
        $Amenity = Amenity::factory()->create();
        $data = [
            'name' => 'new_Amenity'
        ];
        $this->actingAs($admin)->json('patch','/amenities/' . $Amenity->id, $data)
            ->assertStatus(200);
        $this->assertDatabaseCount('amenities',1);
        $this->assertDatabaseHas('amenities',['name' => 'new_Amenity']);
    }
    /** @test */
    public function an_amenity_update_name_is_required()
    {
        $admin = Admin::factory()->create();
        $Amenity = Amenity::factory()->create();
        $data = [
            'name' => ''
        ];
        $this->actingAs($admin)->json('patch','/amenities/' . $Amenity->id, $data)
            ->assertStatus(403);
        $this->assertDatabaseCount('amenities',1);
        $this->assertDatabaseHas('amenities',['name' => $Amenity->name]);
    }
    /** @test */
    public function an_admin_can_delete_an_amenity()
    {
        $this->withoutExceptionHandling();
        $admin = Admin::factory()->create();
        $Amenity = Amenity::factory()->create();
        $this->actingAs($admin)->json('delete','/amenities/'.$Amenity->id)
            ->assertStatus(200);
        $this->assertDatabaseCount('amenities',0);
    }
    /** @test */
    public function a_client_cannot_delete_an_amenity()
    {
        $this->withoutExceptionHandling();
        $client = Client::factory()->create();
        $Amenity = Amenity::factory()->create();
        $this->actingAs($client)->json('delete','/amenities/'.$Amenity->id)
            ->assertStatus(401);
        $this->assertDatabaseCount('amenities',1);
    }
}
