<?php


namespace PropertyType;


use App\Models\Admin;
use App\Models\Client;
use App\Models\PropertyType;
use App\Models\Renter;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Tests\TestCase;

class PropertyTypesTest extends TestCase
{
    use RefreshDatabase;

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
    }

    /** @test */
    public function getting_all_propertyTypes()
    {
        PropertyType::factory(2)->create();
        $response = $this->json('get','/property_types')
            ->assertStatus(200)
            ->assertSee(['success' => true])
            ->assertSee('data')
            ->assertJsonCount(2);

        $this->assertEquals(count($response->json(['data'])),2);
    }
    /** @test */
    public function an_admin_can_add_a_propertyType()
    {
        $admin = Admin::factory()->create();
        $data = [
            'title' => 'NO KIDS'
        ];
        $this->actingAs($admin)->json('post','/property_types', $data)
            ->assertStatus(201);
        $this->assertDatabaseCount('property_types',1);
    }
    /** @test */
    public function a_renter_cannot_add_a_propertyType()
    {
        $renter = Renter::factory()->create();
        $data = [
            'title' => 'NO KIDS'
        ];
        $this->actingAs($renter)->json('post','/property_types', $data)
            ->assertStatus(401);
        $this->assertDatabaseCount('property_types',0);
    }
    /** @test */
    public function a_client_cannot_add_a_propertyType()
    {
        $client = Client::factory()->create();
        $data = [
            'title' => 'NO KIDS'
        ];
        $this->actingAs($client)->json('post','/property_types', $data)
            ->assertStatus(401);
        $this->assertDatabaseCount('property_types',0);
    }
    /** @test */
    public function a_propertyType_title_is_required()
    {
        $admin = Admin::factory()->create();
        $data = [
            'title' => ''
        ];
        $this->actingAs($admin)->json('post','/property_types', $data)
            ->assertStatus(403);
        $this->assertDatabaseCount('property_types',0);
    }
    /** @test */
    public function an_admin_can_update_a_propertyType()
    {
        $admin = Admin::factory()->create();
        $propertyType = PropertyType::factory()->create();
        $data = [
            'title' => 'new_facility'
        ];
        $this->actingAs($admin)->json('patch','/property_types/' . $propertyType->id, $data)
            ->assertStatus(200);
        $this->assertDatabaseCount('property_types',1);
        $this->assertDatabaseHas('property_types',['title' => 'new_facility']);
    }
    /** @test */
    public function a_propertyType_update_title_is_required()
    {
        $admin = Admin::factory()->create();
        $propertyType = PropertyType::factory()->create();
        $data = [
            'title' => ''
        ];
        $this->actingAs($admin)->json('patch','/property_types/' . $propertyType->id, $data)
            ->assertStatus(403);
        $this->assertDatabaseCount('property_types',1);
        $this->assertDatabaseHas('property_types',['title' => $propertyType->title]);
    }
    /** @test */
    public function an_admin_can_delete_a_propertyType()
    {
        $this->withoutExceptionHandling();
        $admin = Admin::factory()->create();
        $propertyType = PropertyType::factory()->create();
        $this->actingAs($admin)->json('delete','/property_types/'.$propertyType->id)
            ->assertStatus(200);
        $this->assertDatabaseCount('property_types',0);
    }
    /** @test */
    public function a_client_cannot_delete_a_propertyType()
    {
        $this->withoutExceptionHandling();
        $client = Client::factory()->create();
        $propertyType = PropertyType::factory()->create();
        $this->actingAs($client)->json('delete','/property_types/'.$propertyType->id)
            ->assertStatus(401);
        $this->assertDatabaseCount('property_types',1);
    }
}
