<?php


namespace Tests\Feature\client;


use App\Models\Client;
use App\Models\Property;
use App\Models\PropertyType;
use App\Models\Renter;
use Carbon\Carbon;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Tests\TestCase;

class ClientRentTest extends TestCase
{
    use RefreshDatabase;
    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->renter = Renter::factory()->create();
        $this->client = Client::factory()->create();
        PropertyType::factory()->create();
    }

    /** @test */
    public function a_client_can_rent_a_property()
    {
        $this->withoutExceptionHandling();
        $data = [
            'start_time' => Carbon::now()->toDateString(),
            'end_time' => Carbon::now()->addDays(5)->toDateString(),
        ];
        $property = Property::factory()->create(['user_id' => $this->renter->id]);

        $this->actingAs($this->client)->json('post','/properties/'. $property->id . '/rent', $data)
            ->assertStatus(201);

        $this->assertDatabaseCount('reservations', 1);
        $this->assertDatabaseHas('reservations',
            [
                'client_id' => $this->client->id,
                'property_id' => $property->id,
                'start_time' => $data['start_time'],
                'end_time' => $data['end_time'],
            ]);
    }

    /** @test */
    public function a_start_time_is_required()
    {
        $this->withoutExceptionHandling();
        $data = [
            'end_time' => Carbon::now()->addDays(2)->toDateString(),
        ];
        $property = Property::factory()->create(['user_id' => $this->renter->id]);

        $this->actingAs($this->client)->json('post','/properties/'. $property->id . '/rent', $data)
            ->assertStatus(403);
        $this->assertDatabaseCount('reservations', 0);
    }
    /** @test */
    public function an_end_time_is_required()
    {
        $this->withoutExceptionHandling();
        $data = [
            'start_time' => Carbon::now()->toDateString(),
        ];
        $property = Property::factory()->create(['user_id' => $this->renter->id]);

        $this->actingAs($this->client)->json('post','/properties/'. $property->id . '/rent', $data)
            ->assertStatus(403);
        $this->assertDatabaseCount('reservations', 0);
    }

    /** @test */
    public function an_start_time_cannot_be_before_today()
    {
        $this->withoutExceptionHandling();
        $data = [
            'start_time' => Carbon::now()->subDays(1)->toDateString(),
            'end_time' => Carbon::now()->addDays(2)->toDateString(),
        ];
        $property = Property::factory()->create(['user_id' => $this->renter->id]);

        $this->actingAs($this->client)->json('post','/properties/'. $property->id . '/rent', $data)
            ->assertStatus(403);
        $this->assertDatabaseCount('reservations', 0);
    }
    /** @test */
    public function an_end_time_cannot_be_before_today()
    {
        $this->withoutExceptionHandling();
        $data = [
            'start_time' => Carbon::now()->toDateString(),
            'end_time' => Carbon::now()->subDays(2)->toDateString(),
        ];
        $property = Property::factory()->create(['user_id' => $this->renter->id]);

        $this->actingAs($this->client)->json('post','/properties/'. $property->id . '/rent', $data)
            ->assertStatus(403);
        $this->assertDatabaseCount('reservations', 0);
    }
    /** @test */
    public function an_end_time_cannot_be_before_or_equals_to_start_time()
    {
        $this->withoutExceptionHandling();
        $data = [
            'start_time' => Carbon::now()->toDateString(),
            'end_time' => Carbon::now()->subDays(2)->toDateString(),
        ];
        $property = Property::factory()->create(['user_id' => $this->renter->id]);

        $this->actingAs($this->client)->json('post','/properties/'. $property->id . '/rent', $data)
            ->assertStatus(403);
        $this->assertDatabaseCount('reservations', 0);
    }

    /** @test */

    public function a_property_status_is_pending_after_client_rent()
    {
        $this->withoutExceptionHandling();
        $data = [
            'start_time' => Carbon::now()->toDateString(),
            'end_time' => Carbon::now()->addDays(2)->toDateString(),
        ];
        $property = Property::factory()->create(['user_id' => $this->renter->id]);

        $this->actingAs($this->client)->json('post','/properties/'. $property->id . '/rent', $data)
            ->assertStatus(201);
        $this->assertDatabaseCount('reservations', 1);
        $this->assertDatabaseHas('properties', ['status' => 'pending']);
    }
}
